apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mongo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-mongo-app
  template:
    metadata:
      labels:
        app: flask-mongo-app
    spec:
      serviceAccountName: flask-mongo-app-sa # Service account for cluster-admin permissions
      containers:
      - name: flask-mongo-app
        image: 162462250454.dkr.ecr.us-east-1.amazonaws.com/antaeuslab/wizrepo:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: "/"
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-mongo-app-sa
  namespace: default # Ensure this matches your deployment's namespace
