apiVersion: v1
kind: Service
metadata:
  name: flask-mongo-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Network Load Balancer
spec:
  type: LoadBalancer
  selector:
    app: flask-mongo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Maps port 80 on the load balancer to port 5000 in the container